### ISSUE TITLE
Can't find manifests in flatpak subdirectory

### ISSUE THREAD

**Issue by cassidyjames** [elementary/action-appcenter-review-find-manifest#2]
I'm not sure if this is a directory recommended by Builder or something, but some apps have their manifests in a `flatpak` directory instead of in the root of the project. This action is failing to find them.

We could either:

- look in a `flatpak` directory as well, if that's a common thing, or
- have a way to just manually specify the path to the manifest, possibly falling back to the current logic if it's unspecified

**Comment by amka** [comment]
I used the `flatpak` directory to structure app sources in case I want to split manifest modules into many flles. Instead of placing all of them in the root directory, I choose the `flatpak` name. It could be any name, Builder is fine to load manifest almost anywhere.

**Comment by btkostner** [comment]
Fixed in https://github.com/elementary/action-appcenter-review-find-manifest/commit/94dd3e79338095dd8c8670252b038d58e02f0003

**Comment by btkostner** [comment]
And released in https://github.com/elementary/action-appcenter-review-find-manifest/releases/tag/v1.2.0
